services:
  swim-spot-checker:
    image: augustinpeyrard/swim-spot-checker:latest
    environment:
      LLM_API_KEY: ${LLM_API_KEY}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SCHEDULE: ${SCHEDULE}
      RECIPIENTS: ${RECIPIENTS}
    volumes:
      - ./data/previous_content:/tmp/previous_content